### ISSUE TITLE
[Problem] `npm run dev` not work

### ISSUE THREAD

**Issue by MarkShawn2020** [zwmmm/react-ssr-36kr#5]
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run dev --scripts-prepend-node-path=auto

> react-ssr-music@1.0.0 dev /Users/mark/WebstormProjects/react-ssr-36kr
> cross-env NODE_ENV=development nodemon ./server/app.js

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn nodemon',
  path: 'nodemon',
  spawnargs: [ './server/app.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-ssr-music@1.0.0 dev: `cross-env NODE_ENV=development nodemon ./server/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-ssr-music@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mark/.npm/_logs/2020-09-17T15_23_14_321Z-debug.log

Process finished with exit code 1

**Comment by MarkShawn2020** [comment]
I do not use it now.
